### ISSUE TITLE
Upon pasting code from external file, the prosql editor doesn't recognize. 

### ISSUE THREAD

**Issue by deep424** [kargirwar/prosql-agent#4]
![image](https://user-images.githubusercontent.com/5990613/135312993-7f3684ce-4329-4202-9665-77e3b9c7d896.png)

**Comment by kargirwar** [comment]
Thanks for writing.

I am not able to replicate the issue.  I pasted query from a file and pressed run. It worked. 
Can you describe in more detail what you did?

**Comment by kargirwar** [comment]
I suspect there was a ";" at the end of query and after pasting the cursor ended up 
beyond the ";". This caused prosql to report empty query error. Moving the cursor to 
anywhere in the middle of query should resolve it. Will be handled in a future release.

**Comment by deep424** [comment]
Yes, it was the ; causing error.
